steps:
  - name: ":docker: :package:"
    plugins:
      docker-compose:
        build: app
        image-repository: 053722134931.dkr.ecr.us-east-1.amazonaws.com/pinterest
    agents:
      queue: elastic-builders
  - wait
  - name: ":eslint:"
    command: yarn run lint
    timeout_in_minutes: 2
    agents:
      queue: elastic
    plugins:
      docker-compose:
        run: app
  - name: ":jest:"
    command: yarn test
    timeout_in_minutes: 2
    agents:
      queue: elastic
    plugins:
      docker-compose:
        run: app
